const galleryTypes = {
  UPLOAD_VIDEO: 'UPLOAD_VIDEO',
  UPLOAD_VIDEO_SUCCESS: 'UPLOAD_VIDEO_SUCCESS',
  UPLOAD_VIDEO_FAIL: 'UPLOAD_VIDEO_FAIL',
  GET_VIDEOS: 'GET_VIDEOS',
  GET_VIDEOS_SUCCESS: 'GET_VIDEOS_SUCCESS',
  GET_VIDEOS_FAIL: 'GET_VIDEOS_FAIL',
  DELETE_VIDEO: 'DELETE_VIDEO',
  DELETE_VIDEO_SUCCESS: 'DELETE_VIDEO_SUCCESS',
  DELETE_VIDEO_FAIL: 'DELETE_VIDEO_FAIL',
};

export default galleryTypes;
